version: "3"
services:
  #APP SERVICES
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: react-lsp-bsi
    restart: unless-stopped
    ports:
      - "1430:80"
    networks:
      - website-discord-kelbuk_default

networks:
  website-discord-kelbuk_default:
    external: true
