version: "3"
services:
  #APP SERVICES
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: template-react-ts
    restart: unless-stopped
    ports: 
        - "1414:80"